# DROP DATABASE BDAV;
CREATE DATABASE BDAV;

USE BDAV;

CREATE TABLE buildings (
	building_id INT,
    survey_date DATE,
    climate_zone VARCHAR(5),
    num_windows INT,
	TOTBTUSPH DECIMAL(30, 2)
);

RENAME TABLE buildings to Homes;

ALTER TABLE Homes ADD hdd65 INT;
ALTER TABLE Homes RENAME COLUMN hdd65 TO HDD_65;
ALTER TABLE Homes MODIFY COLUMN TOTBTUSPH DECIMAL(20, 2);
ALTER TABLE Homes MODIFY COLUMN HDD_65 INT AFTER num_windows;
ALTER TABLE Homes DROP COLUMN HDD_65;

SELECT * FROM Homes;

DROP TABLE Homes;